[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
maxRetries = 3

[env]
NODE_ENV = "production"
PORT = "10000"
CLIENT_URL = "https://code-sync-client.vercel.app"
CORS_ORIGIN = "https://code-sync-client.vercel.app"
MONGODB_URI = "mongodb+srv://radheshshetty0407:%23Shetty222@cluster0.nvc9ek7.mongodb.net/chat-app?retryWrites=true&w=majority" 