services:
  - type: web
    name: code-sync-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://code-sync-client.vercel.app
    healthCheckPath: /health
    autoDeploy: true 