name: Node.js CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Print directory contents
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Server directory contents:"
        ls -la server/
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install dependencies
      working-directory: ./server
      run: npm ci
    
    - name: Build
      working-directory: ./server
      run: npm run build
    
    - name: List build output
      working-directory: ./server
      run: |
        echo "Build output directory contents:"
        ls -la dist/ 